import UIKit

var destinationPlaces: [destinationPlace] = [
    destinationPlace(photoDestination: UIImage(named: "airterjungunungbintan")!, destinationName: "Air Terjun Gunung Bintan", descriptionDestination: "Air terjun ini terletak dalam trek pendakian Gunung Bintan. Airnya jernih dengan nuansa pegunungan yang asri. Tiket masuknya hanya 10.000 rupiah saja. Untuk menuju lokasi, Anda harus berjalan sekitar 300 meter dari pintu masuk. Disana Anda akan menemukan pemandangan air terjun alami yang indah"),
    destinationPlace(photoDestination: UIImage(named: "banyantreebintan")!, destinationName: "Banyan Tree Bintan", descriptionDestination: "Bertengger di atas sebuah tebing dan terletak di lanskap hamparan hijau, Banyan Tree Bintan layaknya gambaran dari berbagai flora dan fauna dengan keramahtamahan yang tulus. Dengan vila-vila yang indah berhiaskan gaya Bali tradisional, resor ini menawarkan pemandangan yang spektakuler dari laut Cina Selatan membentang ke cakrawala. Nikmati ketenangan dan kenyamanan kehidupan pulau resor. Melepas lelah dan bersantai di pantai privat, tee off di lapangan golf kejuaraan dan manjakan diri di spa mewah pemenang penghargaan. Pilihlah dari beragam pilihan olahraga darat dan air, termasuk sepeda motor roda empat, ATV, Jet Ski, Snorkelling dan banyak lagi! Melihat berbagai jenis burung, reptil, dan hewan langka di habitat alami mereka, di bawah perawatan khusus “Penjaga Lingkungan “."),
    destinationPlace(photoDestination: UIImage(named: "ekanganculai")!, destinationName: "Desa Wisata Ekang Anculai", descriptionDestination: "Ekang Anculai merupakan salah satu desa yang ada di kecamatan Teluk Sebong, Kabupaten Bintan, provinsi Kepulauan Riau, Indonesia. Desa wisata Ekang anculai merupakan salah satu contoh desa wisata terbaik di Indonesia yang pernah dikunjungi dan merupakan pilihan lain bagi wisatawan nusantara."),
    destinationPlace(photoDestination: UIImage(named: "gurunpasirbintan")!, destinationName: "Gurun Pasir Bintan", descriptionDestination: " Gurun Pasir Bintan terletak di Dusun Busung, Kecamatan Tanjung Uban, kabupaten Bintan. Gurun ini dulunya bekas penambangan bauksit dan berubah menjadi gurun pasir yang cantik. Karena belum dikembangkan dengan baik, transportasi menuju tempat ini hanya bisa diakses dengan kendaraan pribadi. Begitu pula dengan wisatawan, masih sedikit yang mengunjungi tempat ini karena baru dibuka."),
    destinationPlace(photoDestination: UIImage(named: "hutanmangrove")!, destinationName: "Hutan Mangrove", descriptionDestination: "Di sekitar Pulau Bintan masih sering dijumpai hutan magrove yang masih asri. Bahkan merupakan yang terbesar dan terlengkap di Asia Tenggara. Anda bisa menyusuri hutan bakau ini dengan perahu boat yang disediakan penginapan lokal. Disana Anda akan menemui banyak hewan dan tumbuhan endemik, sekaligus menikmati pemandangan hutan bakau yang masih alami. Biasanya mengunjungi hutan bakau termasuk dalam paket tur di wisata Pantai Trikora."),
    destinationPlace(photoDestination: UIImage(named: "lagoi")!, destinationName: "Treasure bay Lagoi Bintan", descriptionDestination: "Merupakan pulau eksotis dengan pemandangan alam yang masih alami. Di sepanjang pinggiran pantai banyak ditemui resort mewah dan terkenal hingga mancanegara. Salah satu objek wisata terkenal di Lagoi adalah pantainya. Disini Anda akan menggunakan mata uang Singapura alih-alih Rupiah Indonesia. Fasilitasnya lengkap, bahkan sering disamakan dengan resort mewah di Bali."),
    destinationPlace(photoDestination: UIImage(named: "mvdoulosphos")!, destinationName: "MV Doulos Phos", descriptionDestination: "MV Doulus Phos merupakan kapal yang dulunya mengangkut barang ke seluruh dunia. Pemiliknya kemudian menjualnya dan ia menghabiskan waktu terakhirnya di Pelabuhan Bandar Bentan Telani. Kabarnya kapal ini akan berubah menjadi penginapan atau hotel. Anda bisa mengunjungi kapal ini sekaligus mengabadikannya dengan latar belakang matahari terbenam yang cantik."),
    destinationPlace(photoDestination: UIImage(named: "pantaisenggiling")!, destinationName: "Pantai Senggiling", descriptionDestination: "Kawasan pantai ini memang belum setenar pantai-pantai lainnya di Bintan. Penyebabnya adalah akses jalan yang masih susah dijangkau oleh para wisatawan, walaupun letaknya bersebelahan dengan Lagoi, objek wisata terkenal di Bintan. Pantai ini menawarkan ekosistem pantai yang masih alami karena jaranganya wisatawan yang mampir. Pasirnya putih bersih dan terasa lembut di kaki. Bibir pantainya cukup panjang dengan batu-batu besar yang menghiasi."),
    destinationPlace(photoDestination: UIImage(named: "pantaitrikora")!, destinationName: "Pantai Trikora", descriptionDestination: "Anda yang ingin menikmati eksotisnya keindahan batu granit, bisa mengunjungi Pantai Trikora di Bintan dengan garis pantai yang cukup panjang. Disana Anda bisa menemukan pantai yang masih asri, bentangan batu granit serta pondokkan yang tersedia di tepi pantai. Selain berenang, Anda bisa melakukan kegiatan lain, seperti snorkling, menjelajahi garis pantai, berjemur, hingga berteduh di pondokkan untuk menghindari sinar matahari."),
    destinationPlace(photoDestination: UIImage(named: "patungseribu")!, destinationName: "Patung Seribu", descriptionDestination: "Bintan tidak hanya menyediakan berbagai wisata yang sangat menarik. Namun, di Bintan juga terdapat berbagai rumah-rumah ibadah dari beragam keyakinan di Indonesia. Di Bintan terdapat tempat ibadah yang paling unik yaitu Vihara Ksitigrabha Bodhisattva. Vihara ini lebih dikenal dengan sebutan Vihara Patung 1000 wajah. Disebut sebagai Vihara 1000 wajah, dikarenakan terdapat 500 patung murid Budha. Uniknya lagi setiap patung memiliki ekspresi yang berbeda dengan ukuran normal. Ketika menginjakkan kaki di Vihara ini, Anda akan merasa berada di negeri Tiongkok. Pada setiap patung yang terdapat di vihara ini, pada bagian bawah kakinya tertulis nama-nama mereka dari pahatan. Maka dari itu ketika anda ingin merencanakan datang ke wisata Bintan, pastikan tidak melewatkan vihara 1000 wajah ini. Tentunya Anda bisa mengabadikan setiap momen di Vihara ini, karena terdapat banyak spot foto."),
    destinationPlace(photoDestination: UIImage(named: "pulauberalaspasir")!, destinationName: "Pulau Beralas Pasir", descriptionDestination: "Sering disebut sebagai white sand island, pulau ini hanya dihuni oleh beberapa penjaga pulau saja. Selain tidak berpenghuni, hanya merekalah yang merawat dan menjaga pulau ini agar tetap bersih dan rapi. Sebagai saran, Anda bisa mengunjungi tempat ini dengan mengikuti paket wisata dari agen trip lokal karena harganya yang lebih terjangkau. Jika Anda menggunakan paket wisata yang disediakan resort di sekitar Pulau Beralas Pasir, harganya akan lebih mahal."),
    destinationPlace(photoDestination: UIImage(named: "pulaupenyengat")!, destinationName: "Pulau Penyengat", descriptionDestination: "Pulau Penyengat merupakan bekas kekuasaan wilayah Kerajaan Johor. Anda bisa menelusuri berbagai macam bangunan bersejarah yang tersebar di sepanjang pulau, yang paling terkenal adalah Masjid Raya Sultan Riau. Masjid ini dibuat selama 40 tahun dan menampilkan arsitektur yang unik. Warnanya kuning dan hijau akan langsung terlihat jelas kemegahannya ketika Anda menginjakkan kaki di pulau ini."),
    destinationPlace(photoDestination: UIImage(named: "telagabiru")!, destinationName: "Telaga Biru", descriptionDestination: "Telaga Biru Bintan berlokasi di Desa Busung, Kecamatan Tanjung Uban, Kabupaten Bintan. Waktu tempuh dari Tanjungpinang sekitar 45 menit berkendara, sedangkan bila dari Tanjung Uban sekitar 15 menit. Telaga Biru Bintan berada di Provinsi Kepulauan Riau yang menyimpan banyak sisi keindahan. Kecantikan danau ini tidak kalah menarik dengan wisata danau lainnya yang ada di Indonesia."),
    destinationPlace(photoDestination: UIImage(named: "tugusirih")!, destinationName: "Tugu Sirih", descriptionDestination: "Tugu Daun Sirih Emas ini merupakan hasil dari Proyek jalan lingkar Gurindam 12 di tepi laut Kota Tanjungpinang. Tugu itu berdiri kokoh tepat di Zona A1, dan persis di depan Gedung Daerah Tanjungpinang.Tugu setinggi 18 meter itu terbuat dari besi, berwarna kuning emas dan memiliki 7 helai daun dan salah satu daunnya mengarah ke Pulau Penyengat.")
]
